s = set([1, 5, 4, 3, 1])
print(s)
f = open('intrare.txt')
s = set(int(x) for x in f.readline().split())
fs = frozenset(int(x) for x in f.readline().split())
print(fs)
s.discard(5)
print(s)
print(8 not in fs)
print(s.isdisjoint(fs))

